# Generated by Django 3.2.3 on 2022-05-26 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobScraper', '0003_alter_joblisting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobListing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobScraper.joblisting')),
            ],
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=200)),
                ('JobListing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobScraper.joblisting')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobListing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobScraper.joblisting')),
            ],
        ),
    ]
