# Generated by Django 3.2.3 on 2022-05-27 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobScraper', '0005_auto_20220527_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lists',
            name='listName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobScraper.listnames'),
        ),
    ]
