# Generated by Django 3.2.3 on 2022-05-27 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobScraper', '0006_auto_20220527_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobListing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobScraper.joblisting')),
            ],
        ),
        migrations.RemoveField(
            model_name='lists',
            name='JobListing',
        ),
        migrations.AlterField(
            model_name='lists',
            name='listName',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ListNames',
        ),
        migrations.AddField(
            model_name='customlistings',
            name='listName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobScraper.lists'),
        ),
        migrations.AddField(
            model_name='customlistings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
