# Generated by Django 3.2.3 on 2022-06-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobScraper', '0007_auto_20220527_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='aModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afield', models.CharField(max_length=100)),
            ],
        ),
    ]
