# Generated by Django 3.2.3 on 2022-06-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobScraper', '0008_amodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aModel',
        ),
    ]
